name: Build

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yaml
      - CMakeLists.txt
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up ccache
        run: |
          sudo apt-get install -y ccache
          ccache -M 8G
          ccache -o compiler_check=content
      - name: Restore ccache
        uses: actions/cache@v5
        with:
          key: ccache-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: ccache-
          path: ~/.cache/ccache
      - name: CMake configure
        run: cmake -B build -G Ninja -D TT_USE_CCACHE=ON -D CMAKE_BUILD_TYPE=Release
      - name: CMake build
        run: cmake --build build/ --target llvm-final
      - name: Create the archive
        run: |
          cp -r install/llvm-final tt
          tar -cvJf tt.tar.xz tt/
      - name: Print ccache stats
        run: ccache -s
      - name: Upload the archive
        uses: actions/upload-artifact@v7
        with:
          name: tt
          path: tt.tar.xz

  release:
    name: Release
    needs: build
    runs-on: [ubuntu-24.04]
    environment: release
    permissions:
      contents: write  # release publishing
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download the archive
        uses: actions/download-artifact@v8
        with:
          name: tt
      - name: Create a new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_release=$(gh release list --limit 1 --json tagName -q '.[0].tagName')
          next_release=$(( ${latest_release:-0} + 1 ))

          mv tt.tar.xz "tt-${next_release}.tar.xz"
          gh release create "${next_release}" "tt-${next_release}.tar.xz" --notes=
