name: CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yaml
      - CMakeLists.txt

permissions:
  contents: write  # release publishing

jobs:
  build-llvm:
    name: Build LLVM
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: CMake configure
        run: cmake -B build -G Ninja
      - name: CMake build
        run: cmake --build build/ --target llvm-final
      - name: Package binaries
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit=$(git rev-parse --short HEAD)
          name="llvm-${commit}"

          cp -r install/llvm-final "${name}"
          tar -cvJf "${name}.tar.xz" "${name}"
          gh release create "${commit}" "${name}.tar.xz" --notes=
